package com.home_banking_.enums.audit;

public enum TransactionAuditAction implements AuditAction{
    CUSTOMER_DEPOSIT_COMPLETED,
    ADMIN_CREDIT_COMPLETED,
    USER_TRANSACTION_VIEWED,
    TRANSACTION_REJECTED,
    TRANSACTION_REJECTED_INSUFFICIENT_BALANCE,
    WITHDRAW_REJECTED_INSUFFICIENT_BALANCE,
    TRANSFER_COMPLETED,
    WITHDRAW_COMPLETED,

}
