spring:
  application:
    name: home-banking-api

  datasource:
    url: jdbc:mysql://127.0.0.1:3308/banking?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8mb4
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

server:
  port: 8080
  forward-headers-strategy: framework

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    redis:
      enabled: false
    mongo.enabled: false
    cassandra.enabled: false
    elasticsearch.enabled: false
    rabbit.enabled: false
    solr.enabled: false
    ldap.enabled: false
    mail.enabled: false
    influxdb.enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.jdbc: TRACE



