server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://mysql-dev:3306/hb_dev?useSSL=true
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration