
spring.jpa.show-sql=true

#logging.level.org.hibernate.SQL=DEBUG

spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt.secret= ${JWT_SECRET}
application.security.jwt.expiration-ms=${JWT_EXPIRATION:900000}
application.security.jwt.refresh-token.expiration-ms=${JWT_REFRESH_EXPIRATION:1296000000}


logging.level.org.springframework.beans.factory=DEBUG

logging.level.com.home_banking_.security=DEBUG

spring.main.allow-circular-references=true

