spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/banking?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081

management:
  server:
    port: 9090
  endpoints.web.exposure.include: "health,info,metrics,loggers,threaddump,httpexchanges"
  endpoint.health.show-details: always
  endpoint.health.show-components: always
  health:
    redis.enabled: false
    mongo.enabled: false
    cassandra.enabled: false
    elasticsearch.enabled: false
    rabbit.enabled: false
    solr.enabled: false
    ldap.enabled: false
    mail.enabled: false
    influxdb.enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE