server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  endpoint:
    prometheus:
      enabled: true
metrics:
  export:
    prometheus:
      enabled: true