spring:
  main:
    lazy-initialization: true
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

server:
  port: 0  # aleatorio

logging:
  level:
    root: WARN
    com.homebanking: INFO