package com.home_banking_.enums;

public enum TypeNotification {
    CARD_CREATED,
    CARD_BLOCKED,
    CARD_CANCELLED,

    TRANSFER_COMPLETED,
    DEPOSIT_RECEIVED,
    WITHDRAW_COMPLETED,

    PAYMENT_COMPLETED,

    LOAN_REQUESTED,
    LOAN_APPROVED,
    LOAN_REJECTED,

    PASSWORD_CHANGED,
    SUSPICIOUS_LOGIN
}
